### ISSUE TITLE
显示用户错误

### ISSUE THREAD

**Issue by 1690088023** [wintersnowlc/Genshin_login_tool#4]
在查询用户的时候提示
![5450243c9b72172fb5eaf662a967e876](https://github.com/wintersnowlc/Genshin_login_tool/assets/59808553/2596b59a-2fd8-4993-98e3-ba23403d0efa)

**Comment by wintersnowlc** [comment]
你可能添加了一个错误的用户，或者添加晕乎的时候发生了错误，你可以试试删除userinfo.pickle文件后重新添加
